console.log("1: start");
await loadGameData();
console.log("2: data loaded");
initializeUI();
console.log("3: ui");
setupPokemonSearch("attackerPokemon", "attackerSearchBox");
console.log("4: search1");
setupPokemonSearch("defenderPokemon", "defenderSearchBox");
console.log("5: search2");
setupMoveSearch();
console.log("6: move search");
initializeCalculator();
console.log("7: calculator");
